In [9]:
import numpy as np
arr=np.zeros(3)
print(arr)
print()
arr1=np.zeros((2,3))
print(arr1)

[0. 0. 0.]

[[0. 0. 0.]
 [0. 0. 0.]]


In [14]:
arr=np.ones((3,3)) #filling all element by 1 in 3*3 matrices
print(arr)
arr_i=np.eye(3) #identity matrix
print(arr_i)
arr2=np.eye(3,4) #filling all elements 0 other than pricipal diagonal
print(arr2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [19]:
arr=np.diag([1,2,3,4])
print(arr)
arr1=[[1,3,4],[4,5,6],[8,9,10]]
diag_elements=np.diag(arr1) #getting diagonal elements
print(diag_elements)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[ 1  5 10]


In [23]:
#generate a random number within given range
arr=np.random.randint(1,20,3)
print(arr)

[13 14  5]


In [27]:
#rand function
arr=np.random.rand(5) #range is in between 0 to1
print(arr)
arr2d=np.random.rand(2,3) # 2*3 matrix
print(arr2d)

[0.48056123 0.73835587 0.28058597 0.55902501 0.31243261]
[[0.02535025 0.93642714 0.43093501]
 [0.13662326 0.70325618 0.25477704]]


In [28]:
arr2d=np.random.randn(2,3) #values near to 0
print(arr2d)

[[ 0.05479716  0.66821514 -1.02991247]
 [ 0.05521098 -1.67513242 -0.18567619]]
