In [9]:
import numpy as np
#indexing and silecing in 1-d dimesional array
a=[]
size=int(input("Enter the size of array"))
for i in range(size):
    val=int(input("Enter array elements"))
    a.append(val)
arr=np.array(a)    
for i in range(arr.size):
    print(arr[i])
i=sum=0    
for i in range(arr.size):
    sum+=arr[i]
print("Sum of array: ",sum)   
#slicing is same as in list
arr2=arr[2:4]
print(arr2)

Enter the size of array4
Enter array elements4
Enter array elements3
Enter array elements2
Enter array elements1
4
3
2
1
Sum of array:  10
[2 1]


In [16]:
#reshaping of array
arr=np.random.randint(1,50,12)
print(arr)
print(arr.shape)
arr=arr.reshape(2,6) #converting to 2-d array
print(arr)
arr=arr.reshape(4,3)
print(arr)
arr=arr.reshape(2,2,3)
print(arr)
arr.reshape(3,-1) #automatic calculate column
print(arr)
arr.reshape(-1,4)
print(arr)

[48 39 35 48 17  5 47 23 15 20 45 13]
(12,)
[[48 39 35 48 17  5]
 [47 23 15 20 45 13]]
[[48 39 35]
 [48 17  5]
 [47 23 15]
 [20 45 13]]
[[[48 39 35]
  [48 17  5]]

 [[47 23 15]
  [20 45 13]]]
[[[48 39 35]
  [48 17  5]]

 [[47 23 15]
  [20 45 13]]]
[[[48 39 35]
  [48 17  5]]

 [[47 23 15]
  [20 45 13]]]
