In [12]:
import numpy as np
#creating 1-d array
a=[1,2,3,4,5]
myarray=np.array(a)
print(*myarray)
print("Total dimesion: ",myarray.ndim) #dimesion of array
print("Array shape: ",myarray.shape) # returns rows and columns

1 2 3 4 5
Total dimesion:  1
Array shape:  (5,)


In [6]:
a=[]
n=int(input("Enter the size of array: "))
for i in range(n):
    val=int(input("Enter array elements: "))
    a.append(val)
myarray=np.array(a)
print(myarray)
print(type(myarray))

Enter the size of array: 5
Enter array elements: 12
Enter array elements: 13
Enter array elements: 14
Enter array elements: 15
Enter array elements: 16
[12 13 14 15 16]
<class 'numpy.ndarray'>


In [11]:
#creating 2-d array
myarray=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(myarray)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
